
CREATE TABLE "public"."dish" (
  "id" serial4 NOT NULL,
  "name" varchar(100) NOT NULL,
  "preco" float8 NOT NULL,
  CONSTRAINT "PK_dish" PRIMARY KEY ("id")
)
;


-- OU --


CREATE TABLE "public"."dish" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "name" varchar(100) NOT NULL,
  "preco" float8 NOT NULL,
  CONSTRAINT "PK_dish" PRIMARY KEY ("id")
)
;
